"use client";
import { useEffect, useRef, useState } from "react";
import api from "@/lib/api";

type DocType = "receipt" | "invoice" | "proforma";

interface Props {
  transactionId: string;
  onClose: () => void;
}

export default function InvoiceGenerator({ transactionId, onClose }: Props) {
  const [data, setData]   = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [docType, setDocType] = useState<DocType>("receipt");
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    api.get(`/api/v1/inventory/sales/${transactionId}/receipt`)
      .then(r => setData(r.data))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [transactionId]);

  const fmt = (n: number) => `₦${(n || 0).toLocaleString()}`;
  const fmtDate = (iso: string) => iso ? new Date(iso).toLocaleDateString("en-NG", { day:"numeric", month:"long", year:"numeric" }) : "—";

  const DOC_LABELS: Record<DocType, string> = { receipt:"RECEIPT", invoice:"INVOICE", proforma:"PROFORMA INVOICE" };

  const printDoc = () => {
    if (!printRef.current) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>CARSTRIMS ${DOC_LABELS[docType]} — ${transactionId}</title><style>*{box-sizing:border-box}body{margin:0;padding:20px;font-family:Arial,sans-serif;color:#1A1A1A;background:#fff}@media print{body{padding:0}.no-print{display:none}}</style></head><body>${printRef.current.innerHTML}<script>window.onload=()=>window.print()<\/script></body></html>`);
    win.document.close();
  };

  const downloadJpg = async () => {
    if (!printRef.current) return;
    try {
      const { default: html2canvas } = await import("html2canvas").catch(() => ({ default: null }));
      if (!html2canvas) { alert("Export as JPG: open the print dialog and save as PDF/image from there."); return; }
      const canvas = await html2canvas(printRef.current, { scale: 2, backgroundColor: "#fff" });
      const link = document.createElement("a");
      link.download = `CARSTRIMS-${docType}-${transactionId}.jpg`;
      link.href = canvas.toDataURL("image/jpeg", 0.92);
      link.click();
    } catch { alert("Could not export as image. Use Print → Save as PDF instead."); }
  };

  const shareDoc = () => {
    if (!data) return;
    const text = `${DOC_LABELS[docType]}\n${data.dealer?.name||"CARSTRIMS Dealer"}\n${data.car?.brand} ${data.car?.model} ${data.car?.year}\nSelling Price: ${fmt(data.financials?.sellingPrice)}\nTransaction: ${transactionId}\nBuyer: ${data.buyer?.name||"Cash Buyer"}\nDate: ${fmtDate(data.issuedAt)}\n\nGenerated by CARSTRIMS — UASE TECH STUDIO`;
    if (navigator.share) { navigator.share({ title: `CARSTRIMS ${DOC_LABELS[docType]}`, text }); }
    else { navigator.clipboard.writeText(text); alert("Document details copied to clipboard!"); }
  };

  if (loading) return (
    <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1100}}>
      <div style={{background:"#fff",borderRadius:"12px",padding:"2rem",textAlign:"center",display:"flex",flexDirection:"column",gap:"1rem",alignItems:"center"}}>
        <div style={{width:"28px",height:"28px",border:"3px solid #E5E5E5",borderTopColor:"#F47B20",borderRadius:"50%",animation:"spin 0.8s linear infinite"}}/>
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
        <p style={{color:"#737373",fontSize:"0.875rem",margin:0}}>Loading document...</p>
      </div>
    </div>
  );

  if (!data) return null;

  return (
    <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.6)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1100,padding:"1rem",overflowY:"auto"}}>
      <div style={{background:"#fff",borderRadius:"16px",width:"100%",maxWidth:"680px",maxHeight:"92vh",overflowY:"auto",boxShadow:"0 20px 60px rgba(0,0,0,0.25)"}}>
        {/* Controls */}
        <div className="no-print" style={{display:"flex",alignItems:"center",gap:"0.5rem",padding:"1rem 1.25rem",borderBottom:"1px solid #E5E5E5",flexWrap:"wrap",background:"#FAFAFA"}}>
          {(["receipt","invoice","proforma"] as DocType[]).map(t=>(
            <button key={t} onClick={()=>setDocType(t)}
              style={{padding:"0.45rem 0.875rem",borderRadius:"6px",border:"1.5px solid",fontSize:"0.78rem",fontWeight:600,cursor:"pointer",background:docType===t?"#F47B20":"#fff",color:docType===t?"#fff":"#525252",borderColor:docType===t?"#F47B20":"#E5E5E5",transition:"all 0.15s"}}>
              {t.charAt(0).toUpperCase()+t.slice(1)}
            </button>
          ))}
          <div style={{flex:1}}/>
          <button onClick={printDoc} style={{background:"#1A1A1A",color:"#fff",border:"none",borderRadius:"8px",padding:"0.5rem 0.875rem",fontSize:"0.78rem",cursor:"pointer",fontWeight:600,whiteSpace:"nowrap"}}>🖨 Print / PDF</button>
          <button onClick={downloadJpg} style={{background:"#EFF6FF",color:"#3B8BD4",border:"1.5px solid #BFDBFE",borderRadius:"8px",padding:"0.5rem 0.875rem",fontSize:"0.78rem",cursor:"pointer",fontWeight:600,whiteSpace:"nowrap"}}>⬇ JPG</button>
          <button onClick={shareDoc} style={{background:"#F0FDF4",color:"#16A34A",border:"1.5px solid #86EFAC",borderRadius:"8px",padding:"0.5rem 0.875rem",fontSize:"0.78rem",cursor:"pointer",fontWeight:600,whiteSpace:"nowrap"}}>↗ Share</button>
          <button onClick={onClose} style={{background:"#F5F5F5",border:"1.5px solid #E5E5E5",color:"#525252",borderRadius:"8px",padding:"0.5rem 0.75rem",fontSize:"0.78rem",cursor:"pointer"}}>✕</button>
        </div>

        {/* Document */}
        <div ref={printRef} style={{padding:"2rem",background:"#fff"}}>
          {/* Header */}
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"1.5rem",paddingBottom:"1.25rem",borderBottom:"3px solid #F47B20"}}>
            <div style={{display:"flex",alignItems:"center",gap:"1rem"}}>
              {data.dealer?.logo && <img src={data.dealer.logo} alt="" style={{width:"56px",height:"56px",objectFit:"cover",borderRadius:"8px",border:"1px solid #E5E5E5"}}/>}
              <div>
                <div style={{fontFamily:"Georgia,serif",fontSize:"1.1rem",fontWeight:700,color:"#1A1A1A"}}>{data.dealer?.name||"CARSTRIMS Dealer"}</div>
                {data.dealer?.phone && <div style={{fontSize:"0.75rem",color:"#737373"}}>📞 {data.dealer.phone}</div>}
                {data.dealer?.email && <div style={{fontSize:"0.75rem",color:"#737373"}}>✉ {data.dealer.email}</div>}
                {(data.dealer?.city||data.dealer?.state) && <div style={{fontSize:"0.75rem",color:"#737373"}}>📍 {[data.dealer.city,data.dealer.state].filter(Boolean).join(", ")}</div>}
              </div>
            </div>
            <div style={{textAlign:"right"}}>
              <div style={{fontFamily:"Georgia,serif",fontSize:"1.6rem",fontWeight:700,color:"#F47B20",letterSpacing:"0.08em"}}>{DOC_LABELS[docType]}</div>
              <div style={{fontSize:"0.78rem",color:"#737373",marginTop:"0.25rem"}}>#{data.receiptNumber}</div>
              <div style={{fontSize:"0.78rem",color:"#737373"}}>{fmtDate(data.issuedAt)}</div>
            </div>
          </div>

          {/* Parties */}
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}>
            <div>
              <div style={{fontSize:"0.6rem",fontWeight:800,letterSpacing:"0.12em",textTransform:"uppercase" as const,color:"#A3A3A3",marginBottom:"0.4rem"}}>From (Seller)</div>
              <div style={{fontSize:"0.875rem",fontWeight:600,color:"#1A1A1A"}}>{data.dealer?.name||"—"}</div>
              {data.dealer?.address && <div style={{fontSize:"0.78rem",color:"#737373"}}>{data.dealer.address}</div>}
            </div>
            <div>
              <div style={{fontSize:"0.6rem",fontWeight:800,letterSpacing:"0.12em",textTransform:"uppercase" as const,color:"#A3A3A3",marginBottom:"0.4rem"}}>To (Buyer)</div>
              <div style={{fontSize:"0.875rem",fontWeight:600,color:"#1A1A1A"}}>{data.buyer?.name||"Cash Buyer"}</div>
              {data.buyer?.phone && <div style={{fontSize:"0.78rem",color:"#737373"}}>{data.buyer.phone}</div>}
              {data.buyer?.email && <div style={{fontSize:"0.78rem",color:"#737373"}}>{data.buyer.email}</div>}
            </div>
          </div>

          {/* Vehicle */}
          <div style={{background:"#F5F5F5",borderRadius:"10px",padding:"1rem",marginBottom:"1.5rem"}}>
            <div style={{fontSize:"0.6rem",fontWeight:800,letterSpacing:"0.12em",textTransform:"uppercase" as const,color:"#A3A3A3",marginBottom:"0.875rem"}}>Vehicle Details</div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"0.75rem"}}>
              {[["Brand",data.car?.brand],["Model",data.car?.model],["Year",data.car?.year],["Color",data.car?.color||"—"],["VIN",data.car?.vin||"—"],["Car ID",data.car?.carId||"—"]].map(([l,v])=>(
                <div key={l}><div style={{fontSize:"0.6rem",color:"#A3A3A3",fontWeight:600,textTransform:"uppercase" as const,letterSpacing:"0.06em"}}>{l}</div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1A1A1A"}}>{v||"—"}</div></div>
              ))}
            </div>
          </div>

          {/* Financials */}
          <table style={{width:"100%",borderCollapse:"collapse",marginBottom:"1.5rem"}}>
            <thead><tr style={{background:"#1A1A1A",color:"#fff"}}>
              <th style={{padding:"0.625rem 0.875rem",textAlign:"left" as const,fontSize:"0.72rem",fontWeight:600}}>Description</th>
              <th style={{padding:"0.625rem 0.875rem",textAlign:"right" as const,fontSize:"0.72rem",fontWeight:600}}>Amount</th>
            </tr></thead>
            <tbody>
              <tr style={{borderBottom:"1px solid #E5E5E5"}}>
                <td style={{padding:"0.75rem 0.875rem",fontSize:"0.875rem"}}>
                  {data.car?.brand} {data.car?.model} {data.car?.year}<br/>
                  <span style={{fontSize:"0.72rem",color:"#737373"}}>Payment: {data.financials?.paymentMethod?.replace(/_/g," ")||"Cash"}</span>
                </td>
                <td style={{padding:"0.75rem 0.875rem",textAlign:"right" as const,fontFamily:"Georgia,serif",fontSize:"1.1rem",fontWeight:700,color:"#F47B20"}}>{fmt(data.financials?.sellingPrice)}</td>
              </tr>
            </tbody>
            <tfoot><tr style={{background:"#F5F5F5"}}>
              <td style={{padding:"0.875rem",fontWeight:700,fontSize:"0.9rem"}}>TOTAL</td>
              <td style={{padding:"0.875rem",textAlign:"right" as const,fontFamily:"Georgia,serif",fontSize:"1.25rem",fontWeight:700,color:"#F47B20"}}>{fmt(data.financials?.sellingPrice)}</td>
            </tr></tfoot>
          </table>

          {data.financials?.notes && (
            <div style={{background:"#FFF7ED",border:"1px solid rgba(244,123,32,0.2)",borderRadius:"8px",padding:"0.875rem",marginBottom:"1.5rem"}}>
              <div style={{fontSize:"0.62rem",fontWeight:700,textTransform:"uppercase" as const,letterSpacing:"0.1em",color:"#A3A3A3",marginBottom:"0.3rem"}}>Notes</div>
              <div style={{fontSize:"0.875rem",color:"#525252"}}>{data.financials.notes}</div>
            </div>
          )}

          {/* Footer */}
          <div style={{borderTop:"2px solid #E5E5E5",paddingTop:"1rem",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
            <div style={{fontSize:"0.68rem",color:"#A3A3A3",maxWidth:"300px",lineHeight:1.5}}>
              {docType==="proforma"?"This is a proforma invoice and does not constitute a final sale.":"This document serves as proof of sale and is valid for financial records."}
            </div>
            <div style={{textAlign:"right" as const}}>
              <div style={{display:"flex",alignItems:"center",gap:"0.5rem",justifyContent:"flex-end"}}>
                <img src="/logo.png" alt="CARSTRIMS" style={{height:"18px",objectFit:"contain"}}/>
              </div>
              <div style={{fontSize:"0.58rem",color:"#D4D4D4",marginTop:"3px"}}>Powered by UASE TECH STUDIO</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
