#!/bin/sh

# Xcode Cloud checks out a completely fresh copy of the git repo into
# a clean environment for every build - node_modules is (correctly)
# gitignored, so it does not exist here at all until this script
# installs it. Without this, Package.swift's local-path references
# into node_modules/@capacitor/* (how Capacitor's plugins resolve as
# Swift Packages) all fail with "doesn't exist in file system" -
# exactly the failure this script exists to prevent.
set -e

echo "=== ci_post_clone.sh starting ==="

# Xcode Cloud's build runners don't have Node.js installed by
# default - install it via Homebrew, which IS preinstalled on every
# Xcode Cloud macOS image.
brew install node

# Xcode Cloud clones the repo to a path like
# /Volumes/workspace/repository - this script runs from inside
# ios/App/ci_scripts, so climb back up to the actual repo root
# before running any npm/npx commands.
cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "=== Installing node_modules ==="
npm install

echo "=== Syncing Capacitor iOS project ==="
npx cap sync ios

# Real fix from earlier in this project's history, carried forward
# here: npx cap sync silently continuing even when it fails to
# regenerate ios/App/App/capacitor.config.json correctly (e.g. a
# wrong or missing server.url) was the actual root cause of a
# previous black-screen regression - the native shell would ship
# with a stale/incorrect config with no build failure to signal it.
# Verify explicitly that the real production URL made it into the
# generated config, and fail the build loudly here rather than
# shipping a broken binary silently.
CONFIG_PATH="$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/capacitor.config.json"
if [ ! -f "$CONFIG_PATH" ]; then
  echo "ERROR: capacitor.config.json was not generated by cap sync - aborting build."
  exit 1
fi
if ! grep -q "www.carstrims.com" "$CONFIG_PATH"; then
  echo "ERROR: capacitor.config.json does not contain the expected server.url - aborting build."
  cat "$CONFIG_PATH"
  exit 1
fi

echo "=== ci_post_clone.sh finished successfully ==="
