#!/bin/sh
# Xcode Cloud runs this automatically right after cloning the repo,
# before it tries to build/resolve packages. Capacitor's Package.swift
# references ../../../node_modules/@capacitor/* directly, so those
# folders must exist before Xcode's package resolution step runs.
set -e

echo "==> Installing Node.js (Xcode Cloud images don't include it by default)"
brew install node

echo "==> Installing npm dependencies at repo root (including devDependencies)"
cd "$CI_PRIMARY_REPOSITORY_PATH"
# --include=dev is required here: capacitor.config.ts is TypeScript, and the
# Capacitor CLI needs typescript/ts-node (usually devDependencies) to read it.
# Xcode Cloud can default to a production-style install that skips devDependencies,
# which silently breaks `npx cap copy` below with no clear error.
npm install --include=dev

echo "==> Done. node_modules/@capacitor/* should now exist for SPM to resolve."

# The Xcode project's Resources build phase directly references
# ios/App/App/public as a folder that must exist on disk - normally
# populated by `npx cap sync`, which copies the built web app
# (webDir: "out" in capacitor.config.ts) into it. That folder was
# missing entirely, causing "The file 'public' couldn't be opened
# because there is no such file" to fail the whole archive.
#
# Deliberately NOT running a full `next build` here to generate real
# content: this app loads everything remotely via capacitor.config.ts's
# server.url at runtime, so the local bundled copy is only ever a
# fallback that's rarely if ever actually used - not worth the extra
# CI time, or the risk of the build failing here for unrelated reasons
# (missing env vars, a web-side build error) that have nothing to do
# with packaging the native iOS app. A minimal placeholder satisfies
# Xcode's file reference; if the remote server is ever unreachable,
# this is what would very briefly show instead of a hard crash.
echo "==> Creating placeholder web output for Capacitor's public folder"
mkdir -p "$CI_PRIMARY_REPOSITORY_PATH/out"
cat > "$CI_PRIMARY_REPOSITORY_PATH/out/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>CARSTRIMS</title></head>
<body>Loading CARSTRIMS...</body></html>
HTMLEOF

# PREVIOUSLY: this line swallowed any failure from `cap copy` with a bare
# warning, meaning a broken config.ts parse (e.g. from missing devDependencies)
# would fail silently and ship a stale/incorrect capacitor.config.json to
# production with no build-time indication anything was wrong. That's the
# actual root cause of the app going black after being approved and updated:
# the native config never reflected the latest server.url / allowNavigation
# settings from the repo.
#
# NOW: cap copy is allowed to fail loudly (no `|| echo ...` swallow), and we
# explicitly verify its most important output below.
echo "==> Running npx cap copy ios"
npx cap copy ios

echo "==> Verifying capacitor.config.json was generated"
CONFIG_JSON="$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/capacitor.config.json"
if [ ! -f "$CONFIG_JSON" ]; then
  echo "==> FATAL: capacitor.config.json missing after cap copy — native app would run a stale/incorrect config."
  exit 1
fi

echo "==> Verifying capacitor.config.json contains the expected server URL"
if ! grep -q "www.carstrims.com" "$CONFIG_JSON"; then
  echo "==> FATAL: capacitor.config.json does not contain expected server URL (www.carstrims.com)."
  echo "==> Contents of capacitor.config.json for debugging:"
  cat "$CONFIG_JSON"
  exit 1
fi
echo "==> capacitor.config.json verified OK."

# Verify the public folder Xcode actually needs exists, regardless of
# whether the cap copy step above fully succeeded - this is the one
# thing that must not be missing, so don't rely solely on a single
# external command working perfectly.
if [ ! -d "$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/public" ]; then
  echo "==> public folder still missing, creating it directly as a fallback"
  mkdir -p "$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/public"
  cp "$CI_PRIMARY_REPOSITORY_PATH/out/index.html" "$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/public/index.html"
fi

# config.xml is gitignored (ios/.gitignore - "Generated Config
# files") since it's meant to be auto-generated by cap copy/sync from
# capacitor.config.ts, same as public above - but it was ALSO simply
# missing, meaning this step had genuinely never run before. Same
# defensive fallback: verify it landed, create a minimal one directly
# if it somehow didn't.
if [ ! -f "$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/config.xml" ]; then
  echo "==> config.xml still missing, creating it directly as a fallback"
  cat > "$CI_PRIMARY_REPOSITORY_PATH/ios/App/App/config.xml" << 'XMLEOF'
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.uasetechstudio.carstrims" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>CARSTRIMS</name>
    <content src="index.html" />
    <allow-navigation href="*" />
</widget>
XMLEOF
fi
echo "==> public folder and config.xml populated."


# PRIMARY FIX: a Package.resolved file is now committed directly to
# the repo (ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/
# swiftpm/Package.resolved), pinning the one actual remote dependency
# this project has (capacitor-swift-pm@8.4.0 - everything else is a
# local path dependency under node_modules, which doesn't need SPM
# registry resolution). Two earlier attempts at generating this file
# fresh during ci_post_clone.sh (once fatally, once non-fatally) both
# failed to reliably produce a file Xcode's own archive step would
# accept - committing a known-correct one directly sidesteps that
# unreliability entirely.
#
# This resolution step below is now just a DEFENSIVE BACKUP for the
# future: if a new Capacitor plugin gets added later without someone
# remembering to regenerate and commit an updated Package.resolved,
# this at least attempts to patch that gap at build time rather than
# failing outright - but the committed file above is what actually
# fixes today's build.
echo "==> Resolving Swift Package dependencies (defensive backup only - see comment above)"
cd "$CI_PRIMARY_REPOSITORY_PATH/ios/App"
if xcodebuild -resolvePackageDependencies -workspace App.xcodeproj/project.xcworkspace -scheme App; then
  echo "==> Package resolution complete."
else
  echo "==> WARNING: Package resolution step failed (see above for details)."
  echo "==> Continuing anyway - the actual build/archive step may still succeed,"
  echo "==> or will show the real underlying error directly if it doesn't."
fi